version: '2.1'

services:
  mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '12345'
    volumes:
      - ./database/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: '12345'
      ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongo:27017/
    volumes:
      - ./database/mongo_express:/home/user/data
